### ISSUE TITLE
fail to build llvm 6.0.0:Invalid cross-device link

### ISSUE THREAD

**Issue by longwusha** [termoshtt/llvmenv#22]
RUST_BACKTRACE=1 llvmenv build-entry 6.0.0
Download: http://releases.llvm.org/6.0.0/llvm-6.0.0.src.tar.xz
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 18, kind: Other, message: "Invalid cross-device link" }

stack backtrace:
   0:     0x5584273fd95c - backtrace::backtrace::trace::h12afcd4f49378dd1
   1:     0x5584273fcee2 - backtrace::capture::Backtrace::new_unresolved::h92c6cd9e4e754865
   2:     0x5584273fca0f - failure::backtrace::internal::InternalBacktrace::new::hfb19e4189742a117
   3:     0x5584273fcc91 - <failure::backtrace::Backtrace as core::default::Default>::default::hddfd451558b22cb7
   4:     0x5584273fccc8 - failure::backtrace::Backtrace::new::hcf3c736e958043fe
   5:     0x5584271f8b62 - llvmenv::entry::Entry::checkout::h76d7443acf079d5f
   6:     0x5584272069bc - llvmenv::main::hc950b30536fe8523
   7:     0x5584271f0dc6 - std::rt::lang_start::{{closure}}::h0967c90a560327c1
   8:     0x55842741b6c2 - std::rt::lang_start_internal::{{closure}}::hfeaf84249dc76f81
                        at libstd/rt.rs:59
                         - std::panicking::try::do_call::hf721aa74f3e4f06b
                        at libstd/panicking.rs:310
   9:     0x558427444df9 - __rust_maybe_catch_panic
                        at libpanic_unwind/lib.rs:103
  10:     0x5584274292e5 - std::panicking::try::h7ce97b72b588c2e6
                        at libstd/panicking.rs:289
                         - std::panic::catch_unwind::h2bf76b2cd658ccf1
                        at libstd/panic.rs:392
                         - std::rt::lang_start_internal::hc6c1baa40749df74
                        at libstd/rt.rs:58
  11:     0x558427207f63 - main
  12:     0x7fe419019a86 - __libc_start_main
  13:     0x5584271d3ca9 - _start
  14:                0x0 - <unknown>', libcore/result.rs:983:5
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at libstd/sys/unix/backtrace/tracing/gcc_s.rs:49
   1: std::sys_common::backtrace::print
             at libstd/sys_common/backtrace.rs:71
             at libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at libstd/panicking.rs:211
   3: std::panicking::default_hook
             at libstd/panicking.rs:227
   4: std::panicking::rust_panic_with_hook
             at libstd/panicking.rs:477
   5: std::panicking::continue_panic_fmt
             at libstd/panicking.rs:391
   6: rust_begin_unwind
             at libstd/panicking.rs:326
   7: core::panicking::panic_fmt
             at libcore/panicking.rs:77
   8: core::result::unwrap_failed
   9: llvmenv::main
  10: std::rt::lang_start::{{closure}}
  11: std::panicking::try::do_call
             at libstd/rt.rs:59
             at libstd/panicking.rs:310
  12: __rust_maybe_catch_panic
             at libpanic_unwind/lib.rs:103
  13: std::rt::lang_start_internal
             at libstd/panicking.rs:289
             at libstd/panic.rs:392
             at libstd/rt.rs:58
  14: main
  15: __libc_start_main
  16: _start

**Comment by longwusha** [comment]
Is there anywhere try to create a hard link on the disk?

How to solve this problem?

**Comment by TheDan64** [comment]
I'm seeing this same issue on Linux

**Comment by termoshtt** [comment]
I reproduce it. It seems due to `std::fs::rename`:

> This will not work if the new name is on a different mount point.

I am fixing it...

**Comment by termoshtt** [comment]
I've released 0.1.9. Please re-open if not fixed.
