### ISSUE TITLE
LLVM 6.0.1 entry not found

### ISSUE THREAD

**Issue by TheDan64** [termoshtt/llvmenv#25]
When I try:
```shell
$ llvmenv build-entry 6.0.1
Error: ErrorMessage { msg: "Entry does not found: 6.0.1" }
```

But the download is available: http://releases.llvm.org/6.0.1/llvm-6.0.1.src.tar.xz

6.0.0 does find its URL. Version is 0.1.8, and rustc is 1.27.1 & 1.29.0

**Comment by termoshtt** [comment]
I've released 0.1.9. Please re-open if not fixed
