### ISSUE TITLE
llvmenv version raises error "File not found"

### ISSUE THREAD

**Issue by TheDan64** [termoshtt/llvmenv#36]
Whenever I cd into a directory which does not contain a `.llvmenv` file (or in a parent dir), I get this message: `Error: Os { code: 2, kind: NotFound, message: "No such file or directory" }`.

Same thing happens when I use the `llvmenv` binary in a directory which does not contain a `.llvmenv` file(or in a parent dir).

Edit: Seems to happen because of `export LLVMENV_RUST_BINDING=1`

**Comment by termoshtt** [comment]
Thanks report.

Could you try `RUST_BACKTRACE=1 llvmenv prefix` to generate backtrace of this error.
I guess `llvmenv global system` or `llvmenv init` may resolve it.

**Comment by termoshtt** [comment]
I reproduce it. It is due to `llvmenv version` command, and caused by the `llvm-config` command

**Comment by TheDan64** [comment]
Now I just get a new error message: `Error: ErrorMessage { msg: "Cannot parse version: 1-svn331815-1~exp1~20180510084719" }`

`RUST_BACKTRACE=1 llvmenv prefix` doesn't provide any backtrace it seems because it's not panicing but outputting to stdout/err

**Comment by termoshtt** [comment]
> Now I just get a new error message: Error: ErrorMessage { msg: "Cannot parse version: 1-svn331815-1~exp1~20180510084719" }

Hum... I've never thought that the output of `clang --version` can be such complicated one. This is an issue of `llvmenv version` since we have to get a version to generate string `LLVM_SYS_60_PREFIX`. Do you have a correct way to get LLVM major and minor version for your build?

**Comment by TheDan64** [comment]
So it seems like my system installed llvm version produces this: `clang version 6.0.1-svn331815-1~exp1~20180510084719.80 (branches/release_60)` Maybe just ignore anything past the x.y.z bit with a simple regex?

**Comment by termoshtt** [comment]
I've fixed using regex. Could you check 0.1.12?

**Comment by TheDan64** [comment]
The error is gone, but you have a typo which sets the wrong llvm patch version:
https://github.com/termoshtt/llvmenv/blob/27d085dc1dffeb2d12a3257f1f2de80805f0ecfd/src/build.rs#L127
Should probably be `cap[3]`?

**Comment by termoshtt** [comment]
>  Should probably be cap[3]?

:scream:
I've rleased 0.1.13...

**Comment by TheDan64** [comment]
Thanks!
